"""将表迁移到数据库

Revision ID: a46ba2f9a710
Revises: 
Create Date: 2018-05-27 09:46:49.053797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a46ba2f9a710'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('newscategory',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('isDelete', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('userinfo',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('isDelete', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mobile', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=50), nullable=True),
    sa.Column('signature', sa.String(length=200), nullable=True),
    sa.Column('nick_name', sa.String(length=30), nullable=True),
    sa.Column('gender', sa.Boolean(), nullable=True),
    sa.Column('avatar', sa.String(length=50), nullable=True),
    sa.Column('public_count', sa.Integer(), nullable=True),
    sa.Column('follow_count', sa.Integer(), nullable=True),
    sa.Column('isAdmin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('newsinfo',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('isDelete', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('summary', sa.String(length=1000), nullable=True),
    sa.Column('pic', sa.String(length=50), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('click_count', sa.Integer(), nullable=True),
    sa.Column('comment_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['newscategory.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['userinfo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_user_follow',
    sa.Column('origin_id', sa.Integer(), nullable=True),
    sa.Column('follow_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['follow_id'], ['userinfo.id'], ),
    sa.ForeignKeyConstraint(['origin_id'], ['userinfo.id'], )
    )
    op.create_table('newscomment',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('isDelete', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('news_id', sa.Integer(), nullable=True),
    sa.Column('msg', sa.String(length=500), nullable=True),
    sa.Column('like_count', sa.Integer(), nullable=True),
    sa.Column('comment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['newscomment.id'], ),
    sa.ForeignKeyConstraint(['news_id'], ['newsinfo.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['userinfo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_news_collect',
    sa.Column('userinfo_id', sa.Integer(), nullable=True),
    sa.Column('newsinfo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['newsinfo_id'], ['newsinfo.id'], ),
    sa.ForeignKeyConstraint(['userinfo_id'], ['userinfo.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_news_collect')
    op.drop_table('newscomment')
    op.drop_table('tb_user_follow')
    op.drop_table('newsinfo')
    op.drop_table('userinfo')
    op.drop_table('newscategory')
    # ### end Alembic commands ###
